const Colors = {
    wall: "#c3c3c3",
    floor: "#323232",
    fire: "#e25822",
    ice: "#a5f2f3",
    poison: "#45f12c",
    magic: "#8b008b",
    chaos: "#d40f0f",
    wealth: "#c6c6c6",
    gold_metallic: "#d4af37",
    gold_old: "#cfb53b",
    gold_yellow: "#ffdf00",
    red: "#ff0000",
    white: "#ffffff",
    black: "#000000",
    orange: "#aa8811",
    blue: "#0000FF",
    purple: "#440044",
};

export const ActorType = {
    MONSTER: "monster",
    WEAPON: "weapon",
    POTION: "potion",
};

const Levels = [
    {
        domain: "abstracts",
        levelID: 0,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 1,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 2,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 3,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 4,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 5,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 6,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 7,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 8,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 9,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 10,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 11,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 12,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "dungeons",
        levelID: 13,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 14,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 15,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 16,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 17,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 18,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 19,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 20,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 21,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 22,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 23,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 24,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 25,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
    {
        domain: "gates",
        levelID: 26,
        possibleMonsters: [
            "goblin",
            "kobold",
            "orc",
            "dwarf",
            "man",
            "troll",
            "elf",
            "dragon",
            "snake",
        ],
    },
];

const Items = [
    {
        name: "dagger",
        ch: "_",
        col: "#dfd",
        speed: 100,
        domains: [1, 2, 5, 6],
    },
    {
        name: "long sword",
        ch: "}",
        col: "#2f9",
        speed: 100,
        domains: [1, 5, 5, 6],
    },
    {
        name: "knife",
        ch: "-",
        col: "#2f9",
        speed: 100,
        domains: [1, 4, 5, 6],
    },
    {
        name: "orc",
        ch: "+",
        col: "#2f9",
        speed: 100,
        domains: [3, 4, 5, 6],
    },
    {
        name: "orc",
        ch: "(",
        col: "#2f9",
        speed: 100,
        domains: [3, 4, 5, 6],
    },
    {
        name: "orc",
        ch: ")",
        col: "#2f9",
        speed: 100,
        domains: [3, 4, 5, 6],
    },
    {
        name: "orc",
        ch: ")",
        col: "#2f9",
        speed: 100,
        domains: [3, 4, 5, 6],
    },
    {
        name: "blue potion",
        ch: "_",
        col: Colors.blue,
        speed: 100,
        domains: [1, 3],
    },
    {
        name: "purple potion",
        ch: "_",
        col: Colors.purple,
        speed: 100,
        domains: [2, 3, 4, 5],
    },
];

export function getPossibleMonsters(levelID: number): string[] {
    return Levels[levelID].possibleMonsters;
}

const Texts = {
    en: {
        quotes: [
            `He who fights monsters must take care lest he thereby
become a monster`,
            "Live for today, for tomorrow never comes.",
            "Always watch and follow nature",
            "Where many die there is no fear of death",
            "Deceit sleeps with greed",
            "There is nothing sinister in sorcery, only in the hearts of men.",
            "Only he who wanders can find new paths.",
            "Death answers before she is asked. ",
            "The world needs more heroes.",
            "Better unlearned and bright, than erudite and foolish.",
            "Better go without healing, than call for an unskilled healer.",
            "Skill is not a heavy load to carry.",
            "Even the best climber may fall.",
            "There is no death for the honorable, only a change of bodies.",
            "Straight ahead is always shortest, but not always best.",
            "The sky is no less blue only because the blind can not see it.",
            "Death smiles at us all. All a man can do is to smile back.",
            "Nowhere are there more hiding places than in the heart.",
            "What is the use of running when we are not on the right track?",
            "When men speak ill of you, live so that nobody will believe them.",
            "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",
            "Hope is the dreams of the man awake.",
            "He who starts a fight had better do the fighting himself.",
            "Do not cry before you are hurt.",
            "Cowards may die many times before their deaths.",
            "Fear the reckoning of those you have wronged.",
            "He who becomes a sheep will be eaten by the wolf.",
            "The art of living well and the art of dying well is one.",
            "Heroism consists in hanging on one minute longer.",
            "Men brave and generous live the best lives, seldom will they sorrow; then there are fools, afraid of everything, who grumble instead of giving.",
        ],
        poems: [],
    },
    ru: {
        quotes: [
            `He who fights monsters must take care lest he thereby
become a monster`,
            "Live for today, for tomorrow never comes.",
            "Always watch and follow nature",
            "Where many die there is no fear of death",
            "Deceit sleeps with greed",
        ],
        poems: [],
    },
};

// Begin COMMANDS

enum Commands {
    MOVE_UP = "MOVE_UP",
    MOVE_RIGHT = "MOVE_RIGHT",
    MOVE_DOWN = "MOVE_DOWN",
    MOVE_LEFT = "MOVE_LEFT",
    PICK_ITEM = "PICK_ITEM",
    DROP_ITEM = "DROP_ITEM",
    DROP_LAST_ITEM = "DROP_LAST_ITEM",
    QUAFF = "QUAFF",
    OPEN_INVENTORY = "OPEN_INVENTORY",
    WIELD = "WIELD",
    UNWIELD = "UNWIELD",
    THROW = "THROW",
    INVOKE = "INVOKE",
    PRAY = "PRAY",
}

// End COMMANDS

const Settings = {
    programName: "darband",
    version: "0.0.1",
    debug: true,
    test: false,
    mapW: 36,
    mapH: 13,
    windowW: 36,
    windowH: 16,
    logHeight: 8,
    msg: {
        // Message box location
        x: 5,
        y: 0,
    },
    game: {
        winLevel: 0,
        startLevel: 16,
    },
    keybindings: {
        [Commands.MOVE_UP]: "",
        [Commands.MOVE_RIGHT]: "",
        [Commands.MOVE_DOWN]: "",
        [Commands.MOVE_LEFT]: "",
        [Commands.PICK_ITEM]: "",
        [Commands.DROP_ITEM]: "",
        [Commands.DROP_LAST_ITEM]: "",
        [Commands.QUAFF]: "",
        [Commands.OPEN_INVENTORY]: "",
        [Commands.WIELD]: "",
        [Commands.UNWIELD]: "",
        [Commands.THROW]: "",
        [Commands.INVOKE]: "",
        [Commands.PRAY]: "",
    },
};

export { Settings, Colors, Levels, Items, Texts };
